AllCops:
  EnabledByDefault: true
  Exclude:
    - "lib/version.rb"
Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Copyright:
  Enabled: false
  AutocorrectNotice: ""
Bundler/GemComment:
  Enabled: false