name: Lint

on: 
  push:
    branches: 
      - master
  pull_request:
    paths:
      - '**.rb'

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Rubocop checks
      uses: docker://rewindio/github-action-rubocop
